name: Check JSON

on:
    - push
    - pull_request

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v2
        - name: json-lint
          uses: ocular-d/json-linter@0.0.1
