name: Validate JSON

on:
    - push
    - pull_request

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: json-yaml-validate
          uses: GrantBirki/json-yaml-validate@v3.2.1
